
SELECT ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
USING (ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE "%Intact%" and( SEX_UPON_OUTCOME like "%Neutered%" OR SEX_UPON_OUTCOME LIKE "%Spayed%")
GROUP BY ANIMAL_ID

